version: '3.7'

services:
  postgres:
    image: "postgres:13-alpine"
    hostname: "postgres"
    networks:
      - overlay
    environment:
      - POSTGRES_PASSWORD=fdgdfsgds
      - POSTGRES_USER=invest_bot
      - POSTGRES_DB=invest_bot_dev
      - TZ="Europe/Moscow"
    ports:
      - '5449:5432'
    volumes:
      - 'postgres_data_vol:/var/lib/postgresql/data'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - overlay
    restart: unless-stopped
  redis-server:
    image: 'redis'
    ports:
      - "63791:6379"
    environment:
      - REDIS_PASSWORD=asfsaw123dsj
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
  redis-ui:
    image: patrikx3/p3x-redis-ui:2023.4.102
    ports:
      - 37843:7843
    depends_on:
      - redis-server
    volumes:
      - ./redis-sentinel/redis-ui:/settings

volumes:
  redis_data:
  postgres_data_vol:
  pgadmin:
networks:
  overlay: