version: '3.7'

services:
  redis-server:
    image: 'redis'
    ports:
      - "63791:6379"
    environment:
      - REDIS_PASSWORD=asfsaw123dsj
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
  redis-ui:
    image: patrikx3/p3x-redis-ui:2023.4.102
    ports:
      - 37843:7843
    depends_on:
      - redis-server
    volumes:
      - ./redis-sentinel/redis-ui:/settings

volumes:
  redis_data:
networks:
  overlay: